# Generated by Django 5.2.8 on 2025-12-02 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
