# Generated by Django 5.2.8 on 2025-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres_list',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış tür listesi'),
        ),
    ]
