# Generated by Django 5.2.8 on 2025-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_movie_actors_list_movie_director_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres_list',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış tür listesi'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
